import { useNavigate } from 'react-router-dom'
import { Button, Card, Screen } from '../components/ui'
import { useSession } from '../context/SessionContext'

/** Placeholder screens for flows that are out of scope for this iteration. */

export function AdminStub() {
  const navigate = useNavigate()
  const { signOut } = useSession()
  return (
    <Screen title="Admin dashboard">
      <Card>
        <p className="text-sm text-muted">
          The researcher / medical professional dashboard hasn't been built yet. This is a placeholder so the login flow
          works end to end.
        </p>
      </Card>
      <Button variant="secondary" onClick={() => { signOut(); navigate('/', { replace: true }) }}>
        Log out
      </Button>
    </Screen>
  )
}

export function RequestAccessStub() {
  return (
    <Screen title="Request access" back="/">
      <Card>
        <p className="text-sm text-muted">
          Access requests will be handled by the research team. This screen is a placeholder.
        </p>
      </Card>
    </Screen>
  )
}

export function AccessCodeStub() {
  return (
    <Screen title="Access with code" back="/">
      <Card>
        <p className="text-sm text-muted">
          Entering an access code generated by an administrator will be supported once the admin flow exists.
        </p>
      </Card>
    </Screen>
  )
}
